# Generated by Django 2.2.3 on 2019-07-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_songs_time_stamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongsFixed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songs_path', models.CharField(max_length=200)),
            ],
        ),
    ]
